import "./globals.css";
import type { Metadata } from "next";
import { Single_Day, DM_Sans, Roboto } from "next/font/google";

const single_day = Single_Day({
  style: "normal",
  weight: "400",
  variable: "--font-single-day",
});
const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Root Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${single_day.variable} ${dm_sans.variable} ${roboto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
